// This file is automatically generated. Do not edit it directly.
// Compatibility export for older server functions. It deliberately uses the request's
// bearer token with the public Supabase key so Row Level Security remains authoritative.
// A service-role client must never be used for user-scoped Furina memory operations.
import { createClient } from '@supabase/supabase-js';
import { getRequest } from '@tanstack/react-start/server';
import type { Database } from './types';

function createRequestScopedClient() {
  const SUPABASE_URL = process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    throw new Error(`Missing Supabase environment variable(s): ${missing.join(', ')}`);
  }

  const request = getRequest();
  const authorization = request.headers.get('authorization') || '';
  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      headers: authorization ? { Authorization: authorization } : {},
    },
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    },
  });
}

// Kept under the old name so existing Furina server functions do not need a risky bulk rewrite.
// Every property access resolves a client for the current request; RLS and auth.uid() therefore
// decide which rows/functions the caller may use.
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createRequestScopedClient>, {
  get(_, prop) {
    const client = createRequestScopedClient();
    const value = Reflect.get(client, prop, client);
    return typeof value === 'function' ? value.bind(client) : value;
  },
});
